### ISSUE TITLE
Beam starter does not work.

### ISSUE THREAD

**Issue by adgai19** [apache/beam-starter-go#21]
The starter template fails with 
``` 
2023/10/05 12:05:22 starting worker go
2023/10/05 12:05:22 error talking to provision service worker, using defaults: failed to get manifest: rpc error: code = Unimplemented desc = unknown service org.apache.beam.model.fn_execution.v1.ProvisionService
```
the offending commit looks to be 38985b4ba97cfded823747f13ab4c3097b83bcdd. I guess it would fail because the default runner has been changed from direct to prism runner.

**Comment by lostluck** [comment]
The starter template shouldn't be using Java at all so that's confusing.

We've just updated the quickstart to 2.54.0, and set the new min Go version to 1.22 since there were some new standard library package dependencies that slipped in along the way ("maps", and "slices"). I've run through https://beam.apache.org/get-started/quickstart/go/ and it now works as described.

Thank you for the report, and patience in the time it took for us to spot this.
